# Generated by Django 4.2 on 2024-04-08 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TraderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="user_profiles/default_user.png",
                        null=True,
                        upload_to="user_profiles/",
                    ),
                ),
                (
                    "funds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_invested",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_returns",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
