# Generated by Django 4.2 on 2024-04-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "alphatrader",
            "0003_traderprofile_funds_traderprofile_total_invested_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="traderprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/user-default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
