# Generated by Django 4.2 on 2024-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alphabots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucket",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="stocksymbol",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="stocksymbol",
            name="symbol",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
