# Generated by Django 4.2 on 2024-04-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alphabots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtesting",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
