# Generated by Django 4.2 on 2024-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alphabots", "0002_alter_bucket_name_alter_stocksymbol_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backtesting",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tradingbot",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
