# Generated by Django 4.2 on 2024-04-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alphatrader", "0001_initial"),
        ("alphabots", "0003_alter_backtesting_name_alter_strategy_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alphatrader.traderprofile",
            ),
        ),
        migrations.AlterField(
            model_name="tradingbot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alphatrader.traderprofile",
            ),
        ),
    ]
