# Generated by Django 4.2 on 2024-04-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alphabots", "0004_alter_bucket_user_alter_tradingbot_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backtesting",
            name="bot",
        ),
        migrations.RemoveField(
            model_name="backtesting",
            name="strategy",
        ),
        migrations.AddField(
            model_name="backtesting",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="strategy",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
