# Generated by Django 4.2 on 2024-04-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "alphabots",
            "0005_remove_backtesting_bot_remove_backtesting_strategy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
