# Generated by Django 4.2 on 2024-04-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alphabots", "0006_alter_strategy_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
