# Generated by Django 4.2 on 2024-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alphabots", "0007_kpi"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingbot",
            name="amount_invested",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="tradingbot",
            name="current_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
